server:
  port: 8080
#  servlet:
#    context-path: /

spring:
  profiles:
#    active: local
    active: aws

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    default-property-inclusion: non_null